# Generated by Django 4.2.3 on 2023-07-31 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='create_day',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='files',
            new_name='loaded_file',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='update_day',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='number',
            new_name='no',
        ),
        migrations.RemoveField(
            model_name='board',
            name='writer',
        ),
        migrations.AddField(
            model_name='board',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
